// src/routes/roms/index.svelte
<div class='h-[5em]' />
<div class='flex flex-row nowrap justify-center align-middle text-center'>
  <div class='flex flex-col justify-between'>
    <h1 class='font-serif text-8xl font-bold tracking-wider pb-16'>ROMs</h1>
    <div class="h-2" />
    <div class='pt-4 text-4xl flex flex-col gap-5'>
      <span class='font-mono text-secondary'><a href='https://newchallenger.net/fc2/fc2roms.zip'>FC2 JSONs</a></span>
      <span class='font-mono text-secondary'><a href="https://drive.google.com/uc?export=download&id=1KNzlMznYli9wlM6qhYXEvD2uQHJ6PtDE">jojoba</a></span>
      <span class='font-mono text-secondary'><a href="https://drive.google.com/uc?export=download&id=1DbnTTWDMFzGPEpa7v9UcU41PxQ3FwfQx">jojobanr1</a></span>
      <div class='h-[2em]' />
      <span class='font-mono text-secondary text-2xl'><a href="https://krypton.sh/">Coming Soon</a></span>
    </div>
  </div>
</div>

// src/pages/ROMs.vue
<template>
  <q-page class="flex">
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Space+Mono&display=swap"
      rel="stylesheet"
    />
    <div class="fit column items-center">
      <div id="pagetitle" class="text-h2">ROMs</div>
    </div>
    <div
      class="itemlist fit column inline wrap justify-center items-center content-center"
    >
      <div class="text-h3 q-pb-lg">Fightcade 2</div>
      <div class="text-h4">
        <q-item clickable
          ><a href="https://newchallenger.net/fc2/fc2roms.zip"
            >FC2 JSONs</a
          ></q-item
        >
      </div>
      <div class="text-h4">
        <q-item clickable
          ><a
            href="https://drive.google.com/uc?export=download&id=1KNzlMznYli9wlM6qhYXEvD2uQHJ6PtDE"
            >JOJOBA</a
          ></q-item
        >
      </div>
      <div class="text-h4">
        <q-item clickable
          ><a
            href="https://drive.google.com/uc?export=download&id=1DbnTTWDMFzGPEpa7v9UcU41PxQ3FwfQx"
            >JOJOBANR1</a
          ></q-item
        >
      </div>
    </div>
    <div
      class="itemlist fit column inline wrap justify-center items-center content-right"
    >
      <div class="text-h3 q-pb-lg">Other</div>
      <div class="text-h4">
        <q-item clickable @click="$router.replace('/awa')">Other</q-item>
      </div>
    </div>
  </q-page>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "PageIndex",
});
</script>
